sudo: enabled
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - git
    - gcc-multilib
    - g++-multilib
    - software-properties-common
    - gcc-snapshot
    - g++-6-multilib
    - g++-6-multilib 
    - gcc-6 
    - g++-6 
    - libssl-dev:i386 
    - libboost-all-dev 
    - libc6-dev:i386 
    - gdb 
    - libsdl2-dev 
    - libglew-dev:i386 
    - libglew-dev 
    - libfreetype6-dev=2.5.2-1ubuntu2.8
    - libfreetype6-dev:i386=2.5.2-1ubuntu2.8
    - cmake 
    - libpng-dev 
    - libssl-dev 
    - gcc-multilib 
    - g++-multilib
script:
  - "cd libglez;mkdir build;cd build;cmake ..;make;sudo make install;cd ..;cd .."
  - "cd libxoverlay;mkdir build;cd build;cmake ..;make;sudo make install;cd ..;cd .."
  - "cd simple-ipc;mkdir build;cd build;cmake ..;make;sudo make install;cd ..;cd .."
  - "mkdir build; cd build; cmake ..; make; cd .."
